### ISSUE TITLE
The page isn't responding

### ISSUE THREAD

**Issue by rmlzy** [antfu/vite-plugin-inspect#1]
Hi, this plugin is very cool! Thanks for your work.
I applied it to my project, and then there was a problem.

The page may be stuck when I click below link:
![image](https://user-images.githubusercontent.com/33822612/132969845-6d4d49f2-0a5e-4b89-9fc1-b48991503108.png)

Here is my repo: https://github.com/rmlzy/ChiSha, Thank you for your help:)

**Comment by antfu** [comment]
I might need to disable diff automatically when dealing with large files
