### ISSUE TITLE
in file dist/index.cjs  const lodashEs = require('lodash-es') is error 

### ISSUE THREAD

**Issue by codeflyA** [antfu/vite-plugin-inspect#105]
### Describe the bug

in file dist/index.cjs  use  const lodashEs = require('lodash-es') is error 
node_modules\vite-plugin-inspect\dist\index.cjs not supported.
vite-plugin-inspect\dist\index.cjs to a dynamic import() which is available in all CommonJS modules.
the error happen in 0.8.2

### Reproduction

when i use vite-plugin-vue-devtools the error happen

### System Info

```Shell
"vue": "^3.3.4",
"vite": "^4.3.9",
"vite-plugin-vue-devtools": "7.0.6",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyong-y** [comment]
me too
