### ISSUE TITLE
打开http://localhost:11000/__inspect/，无法显示检查模块的页面

### ISSUE THREAD

**Issue by aipeli** [antfu/vite-plugin-inspect#22]
![inspect](https://user-images.githubusercontent.com/43819745/157686479-0184c121-e6c3-442d-85f2-7086af1ebe5d.png)

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
