### ISSUE TITLE
配置了vite-plugin-html插件之后，访问__inspect就无效了

### ISSUE THREAD

**Issue by free-pan** [antfu/vite-plugin-inspect#24]
### 问题
配置了vite-plugin-html插件之后，访问 __inspect 就无效了

### 期望的结果
和vite-plugin-html插件一起使用，也能正常访问 http://localhost:3000/__inspect/ 界面

**Comment by antfu** [comment]
I don't think it's a problem on our side. Please report to vite-plugin-html instead.
