### ISSUE TITLE
Use the plugin, and has a error when starting dev server

### ISSUE THREAD

**Issue by xianer0405** [antfu/vite-plugin-inspect#26]
$ npm run dev

> vite-app@0.0.0 dev /Users/jxxx/vite-plugin-development
> vite --host

failed to load config from /Users/xxx/-vite-plugin-development/vite.config.ts
error when starting dev server:
/Users/jackie/workspace/learn/vue3/juejin-book-vite/12-vite-plugin-development/node_modules/.pnpm/vite-plugin-inspect@0.4.3_vite@2.9.5/node_modules/vite-plugin-inspect/dist/index.cjs:42
        const result = typeof _result === "string" ? _result : _result?.code;
                                                                       ^
**SyntaxError: Unexpected token '.'**

**Comment by antfu** [comment]
Upgrade your Node version. Node 12 will be EOL soon.

**Comment by xianer0405** [comment]
> Node 12 will be EOL soon



> Upgrade your Node version. Node 12 will be EOL soon.

Thank you!  It's work
