### ISSUE TITLE
Inspect SSR transform

### ISSUE THREAD

**Issue by antfu** [antfu/vite-plugin-inspect#34]
### Clear and concise description of the problem

https://github.com/antfu/vite-plugin-inspect/issues/33#issuecomment-1211536957 by @nksaraf

### Suggested solution

I guess currently we don't distinguish between client and SSR transform. We might need two maps storing them based on `ctx.ssr` flag and offering a new tab on UI for inspecting SSR transform diff.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sapphi-red** [comment]
Maybe this issue can be closed by d89620dde54d1a54de64ead666c93ee18d3f4b2e?
