### ISSUE TITLE
[0.7.3] Vite No HMR

### ISSUE THREAD

**Issue by kingyue737** [antfu/vite-plugin-inspect#43]
### Describe the bug

No HMR

Modify something in the project and you will find the site is not reloaded

### Reproduction

https://stackblitz.com/edit/vitejs-vite-3mqzjg

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by razorness** [comment]
Can confirm this issue. Base of my project is the Vitesse template and I deactivated everything until I found out that inspect plugin disables HMR.
