### ISSUE TITLE
feat: weighted graph nodes

### ISSUE THREAD

**Issue by gabrielcsapo** [antfu/vite-plugin-inspect#64]
### Clear and concise description of the problem

It would be cool if we could make another toggle mode, to make the size of the graph nodes be representative of the time it took.

<img width="1355" alt="Screenshot 2023-03-25 at 12 12 41 PM" src="https://user-images.githubusercontent.com/1854811/227736833-aa6e26fb-5244-4db9-83a5-0a923b1a9e23.png">

### Suggested solution

This would just use the total time of the node to grow the node in relation to other nodes.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
closed via #76
