### ISSUE TITLE
open mode

### ISSUE THREAD

**Issue by CHOYSEN** [antfu/vite-plugin-inspect#69]
### Clear and concise description of the problem

hi, i'm using `--debug` with this plugin, and i can not saw the server url

### Suggested solution

provide a argument to control whether to automatically open the `/__inspect/`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
With `--open=/__inspect/`, Vite will already open it right?

**Comment by CHOYSEN** [comment]
yep, but actually i want to launch two tabs

**Comment by CHOYSEN** [comment]
In addition, I also hope to pop up the inspect page after build.

**Comment by antfu** [comment]
Ok, I think we could have the `open` option in the config. PR welcome

**Comment by userquin** [comment]
closed via #74
