### ISSUE TITLE
Add manual drag and sort function to function items in the toolbar bar

### ISSUE THREAD

**Issue by sincely** [antfu/vite-plugin-inspect#75]
### Clear and concise description of the problem

Perhaps most people prefer sorting custom feature items, such as placing insectors at the top or left, and so on

### Suggested solution

![截图](https://github.com/antfu/vite-plugin-inspect/assets/40814642/98a96837-41da-4ef2-9969-2aa64c73d6db)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Wrong repo to report. Please go https://github.com/webfansplz/vite-plugin-vue-devtools instead.

**Comment by sincely** [comment]
sorry,this is my mistakes!!
