### ISSUE TITLE
Add a button "Debug sourcemaps" to open current file on evanw.github.io/source-map-visualization

### ISSUE THREAD

**Issue by remorses** [antfu/vite-plugin-inspect#78]
### Clear and concise description of the problem

Debugging sourcemaps issues is very difficult especially in ssr mode

### Suggested solution

We could add a button "Debug sourcemaps" that opens a link with the current file and sourcemaps on https://evanw.github.io/source-map-visualization to see what mappings are wrong

source-map-visualization is stateless, it takes the js file and map from the url encoded as base64 (and some more characters for delimiting i assume)

### Additional context

Makes it easier to debug issues like this https://github.com/withastro/astro/issues/5465

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds good to me. We could even using iframe if it's possible. PR welcome :)
