### ISSUE TITLE
Upgrade to 0.7.39 caused fatal nuxt start error

### ISSUE THREAD

**Issue by daniluk4000** [antfu/vite-plugin-inspect#97]
### Describe the bug

The error occured after lockfile maintenance with devtools installed.

 Cannot start nuxt:  The requested module 'vite-plugin-inspect' does not provide an export named 'default'                                                                                                                                                                                     

  import Inspect from 'vite-plugin-inspect';
  ^^^^^^^
  SyntaxError: The requested module 'vite-plugin-inspect' does not provide an export named 'default'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

![image](https://github.com/antfu/vite-plugin-inspect/assets/10450717/9ab1b8a0-2bc2-4071-9c8a-5f5f753b3d77)

Workaround: In package.json

```json
{
  "resolutions": {
    "vite-plugin-inspect": "0.7.38"
  }
}
```

### Reproduction

https://github.com/daniluk4000/nuxt-3.4.2-docker-error (simply run yarn + yarn dev)

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 9.82 GB / 11.68 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 3.6.3 - /usr/bin/yarn
    npm: 10.0.0 - /usr/local/bin/npm
    pnpm: 7.25.1 - /usr/bin/pnpm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ptmkenny** [comment]
I'm also getting a similar error with vite and an Ionic React app:

```
 ERROR  failed to load config from /Users/private/d/ionic/vite.config.ts                                                                                                   08:29:59


 ERROR  error during build:                                                                                                                                                08:29:59
TypeError: (0 , import_vite_plugin_inspect.default) is not a function
    at vite_config_default (/Users/private/d/ionic/vite.config.ts:95:46)
    at loadConfigFromFile (file:///Users/private/d/ionic/node_modules/vite/dist/node/chunks/dep-df561101.js:66089:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///Users/private/d/ionic/node_modules/vite/dist/node/chunks/dep-df561101.js:65682:28)
    at async build (file:///Users/private/d/ionic/node_modules/vite/dist/node/chunks/dep-df561101.js:47852:20)
    at async CAC.<anonymous> (file:///Users/private/d/ionic/node_modules/vite/dist/node/cli.js:822:9)
```

**Comment by nikitavoloboev** [comment]
I tried this fix and it did not work. Hitting same build error.

<img width="648" alt="image" src="https://github.com/antfu/vite-plugin-inspect/assets/6391776/26021c96-d146-44c3-85ff-7ce45f2f83c3">

Commit with the 'fix': https://github.com/learn-anything/learn-anything.xyz/commit/f1437ae47e69e0b789daf4c23c8e8caa9958fca5

**Comment by rlightner** [comment]
I was able to get around using this in package.json:

```
  "overrides": {
    "vite-plugin-inspect": "0.7.38"
  },
```
