### ISSUE TITLE
Transform stack for custom virtual modules are not present

### ISSUE THREAD

**Issue by Malien** [antfu/vite-plugin-inspect#98]
### Describe the bug

I have a custom loader that intercepts funky-looking import specifiers, ala: `import foo from "prefix:some-argument"`.

```js
const prefix = "custom-loader:";

export default function customLoader() {
  return {
    name: "custom-loader",

    resolveId(id) {
      if (id.startsWith(prefix)) return "\0" + id;
    },

    load(id) {
      if (!id.startsWith("\0")) return;
      if (!id.slice(1).startsWith(prefix)) return;
      const arg = id.slice(1 + prefix.length);
      return `export default ${JSON.stringify(arg)}`;
    },
  };
}
```

vite.config.js
```js
import { defineConfig } from "vite";
import customLoader from "./custom-loader.mjs";
import Inspect from "vite-plugin-inspect";

export default defineConfig({
  plugins: [customLoader(), Inspect()],
});
```

As per rollup [convention](https://rollupjs.org/plugin-development/#conventions):
> If your plugin uses 'virtual modules' (e.g. for helper functions), prefix the module ID with \0. This prevents other plugins from trying to process it.

But the transform stack of such virtual modules are empty (aka. I cannot see the result of a `load` step)
![Screenshot 2023-10-05 at 18 28 09](https://github.com/antfu/vite-plugin-inspect/assets/7205038/3bd75eec-0756-4424-ab18-bab490b64f01)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-g5udhe?file=custom-loader.mjs

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by spaceemotion** [comment]
Just stumbled upon this as well. As a workaround i have to use a simple `console.log` in the meantime.

**Comment by justin-schroeder** [comment]
Interesting — I just ran a quick trace on this and it seems the hijack for `load` doesn’t work on custom virtual modules. The result of this line is `null`:

https://github.com/antfu/vite-plugin-inspect/blob/main/src/node/hijack.ts#L104

**Comment by userquin** [comment]
The virtual module content not added to the recorder since the rollup filter is returning false: we need to apply the filter in `resolveId` hook, the filter should be applied to the original id and not in the resolved id.

**Comment by userquin** [comment]
Playground working after updating to latest 0.8.4 release: https://stackblitz.com/edit/vitejs-vite-qu7ibm?file=package.json,vite.config.js
